---
before_install:
  - 'sudo apt-get -qq update'
  - 'pip install -r requirements.txt'
cache:
  directories:
    - '$HOME/.cache/pre-commit'
language: 'python'
script:
  - 'workflow/onboarding.sh'
  - 'workflow/ci.sh'
services:
  - 'docker'
sudo: 'required'
