---
- name: Configure the Buildkite APT key
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 32A37959C2FA5C3C99EFBC32A79206696452D198
    state: present

- name: Configure the Buildkite APT repository
  apt_repository:
    repo: "deb https://apt.buildkite.com/buildkite-agent stable main"
    state: present

- name: Install Latest Buildkite Agent
  apt:
    pkg: "buildkite-agent"
    state: present
  when: buildkite_agent_allow_latest == True

- name: Install Buildkite Agent
  apt:
    pkg: "buildkite-agent={{ buildkite_agent_version }}-{{ buildkite_agent_build_number }}"
    state: present
  when: buildkite_agent_allow_latest == False

- name: Configure Buildkite
  template:
    src: "buildkite-agent.cfg.j2"
    dest: "{{ buildkite_agent_conf_dir[ansible_os_family] }}/buildkite-agent.cfg"
    owner: buildkite-agent
    group: buildkite-agent
    mode: "0600"
  notify:
    - restart-systemd-buildkite

- name: Create systemd unit override directory
  file:
    path: /etc/systemd/system/buildkite-agent.service.d
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Create systemd unit override
  template:
    src: "{{ buildkite_agent_systemd_override_template }}"
    dest: /etc/systemd/system/buildkite-agent.service.d/100-set-start-spawn.conf
    owner: root
    group: root
    mode: "0644"
  notify:
    - restart-systemd-buildkite

- name: Create buildkite-agent service instance
  systemd:
    name: buildkite-agent
    state: "{{ buildkite_agent_allow_service_startup[ansible_os_family] | ternary('started', 'stopped') }}"
    enabled: true
    daemon_reload: true
