---
# https://buildkite.com/docs/agent/v3/osx
# TODO:
# * Conditionally upgrade when already present - `brew update && brew upgrade buildkite-agent`
- name: Add buildkite's tap
  homebrew_tap:
    name: buildkite/buildkite
    state: present

# Workaround for currently broken homebrew release of 2.3.0
- name: Checkout the latest working commit of homebrew
  command: git checkout 2.2.17 
  args:
    chdir: /usr/local/Homebrew

- name: Install buildkite-agent
  homebrew:
    name: buildkite-agent
    update_homebrew: no
  environment:
    HOMEBREW_NO_AUTO_UPDATE: 1

- name: Configure Buildkite
  template:
    src: "buildkite-agent.cfg.j2"
    dest: "{{ buildkite_agent_conf_dir[ansible_os_family] }}/buildkite-agent.cfg"
    mode: "0600"
  notify:
    - "Restart Buildkite Agent and Register for Login"

- name: Set environment hook to load bash profile for test runs
  template:
    src: "buildkite-agent-hook-environment.sh"
    dest: "{{ buildkite_agent_hooks_dir[ansible_os_family] }}/environment"
    mode: "0600"
  when: buildkite_agent_load_bash_profile == True
  notify:
    - "Restart Buildkite Agent and Register for Login"

- name: Refresh homebrew to original state
  command: /usr/local/bin/brew update

