---
# https://buildkite.com/docs/agent/v3/osx
# TODO:
# * Conditionally upgrade when already present - `brew update && brew upgrade buildkite-agent`
- name: Add buildkite's tap
  homebrew_tap:
    name: buildkite/buildkite
    state: present

- name: Install buildkite-agent
  homebrew:
    name: buildkite-agent
    state: latest
    update_homebrew: yes

- name: Configure Buildkite
  template:
    src: "buildkite-agent.cfg.j2"
    dest: "{{ buildkite_agent_conf_dir[ansible_os_family] }}/buildkite-agent.cfg"
    mode: "0600"
  notify:
    - "Restart Buildkite Agent and Register for Login"

- name: Set environment hook to load bash profile for test runs
  template:
    src: "buildkite-agent-hook-environment.sh"
    dest: "{{ buildkite_agent_hooks_dir[ansible_os_family] }}/environment"
    mode: "0600"
  when: buildkite_agent_load_bash_profile == True
  notify:
    - "Restart Buildkite Agent and Register for Login"
