---
- name: restart-systemd-buildkite
  systemd:
    name: "{{ buildkite_agent_username }}"
    state: restarted
  when: ansible_os_family == "Debian" and buildkite_agent_allow_service_startup[ansible_os_family]

- name: restart-windows-buildkite
  win_service:
    name: "{{ buildkite_agent_username }}"
    state: restarted
  when: ansible_os_family == "Windows" and buildkite_agent_allow_service_startup[ansible_os_family]

- name: Restart Buildkite Agent and Register for Login
  command: /usr/local/bin/brew services restart buildkite/buildkite/buildkite-agent
  when: ansible_os_family == "Darwin" and buildkite_agent_allow_service_startup[ansible_os_family]

- name: Start Buildkite Agent and Register for Login
  command: /usr/local/bin/brew services start buildkite/buildkite/buildkite-agent
  when: ansible_os_family == "Darwin" and buildkite_agent_allow_service_startup[ansible_os_family]
